version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8000/
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
